/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package classes;

/**
 *
 * @author gabri
 */
public class telaGenio extends javax.swing.JFrame {

    /** Creates new form telaGenio */
    public telaGenio() { //Construtor
        initComponents();
        lblMsg.setText("<html> Vou pensar em um número entre <strong>1 "
                + "e 5</strong>. Tente adivinhar qual é. </html>");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblGenio = new javax.swing.JLabel();
        spnNum = new javax.swing.JSpinner();
        btnClique = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(380, 400));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Valor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 263, -1, -1));

        lblGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/Akinator100.png"))); // NOI18N
        getContentPane().add(lblGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 90, 150));

        spnNum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spnNum.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spnNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 260, 75, -1));

        btnClique.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClique.setText("Palpite");
        btnClique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliqueActionPerformed(evt);
            }
        });
        getContentPane().add(btnClique, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 312, -1, -1));

        lblMsg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMsg.setText("frase");
        getContentPane().add(lblMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 140, 90));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/Balão de Fala200.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCliqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliqueActionPerformed
        // TODO add your handling code here:
        double ran = Math.random();
        // System.out.println(ran);
        double numran = Math.round(1 + ran * (5-1)); //Usando mínimo + random()*(máximo-mínimo) para número random
        int num = Integer.parseInt(spnNum.getValue().toString());
        String res = (numran == num)? "ACERTOU!":
                String.format("Errou! Pensei em %.0f", numran);
        lblMsg.setText(res);
        
    }//GEN-LAST:event_btnCliqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClique;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblGenio;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JSpinner spnNum;
    // End of variables declaration//GEN-END:variables

}
