/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cursoemvideo;

/**
 *
 * @author gabri
 */
public class TelaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() {
        initComponents(); //Construtor
        panCalc.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNum = new javax.swing.JSpinner();
        btnClique = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        panCalc = new javax.swing.JPanel();
        potRes = new javax.swing.JLabel();
        raqRes = new javax.swing.JLabel();
        racRes = new javax.swing.JLabel();
        ablRes = new javax.swing.JLabel();
        lblAbl = new javax.swing.JLabel();
        lblPot = new javax.swing.JLabel();
        lblRaQ = new javax.swing.JLabel();
        lblRaC = new javax.swing.JLabel();
        divRes = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Super Calculadora");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Informe um valor");

        txtNum.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));

        btnClique.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClique.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Calcularicon30.png"))); // NOI18N
        btnClique.setText("Calcular");
        btnClique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliqueActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Calculadora150.png"))); // NOI18N

        potRes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        potRes.setForeground(new java.awt.Color(0, 0, 255));
        potRes.setText("0");
        potRes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        raqRes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        raqRes.setForeground(new java.awt.Color(0, 0, 255));
        raqRes.setText("0");
        raqRes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        racRes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        racRes.setForeground(new java.awt.Color(0, 0, 255));
        racRes.setText("0");
        racRes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        ablRes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ablRes.setForeground(new java.awt.Color(0, 0, 255));
        ablRes.setText("0");
        ablRes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblAbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAbl.setText("Valor Absoluto");
        lblAbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblPot.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPot.setText("Elevado ao Quadrado");
        lblPot.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblRaQ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRaQ.setText("Raiz Quadrada");
        lblRaQ.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblRaC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRaC.setText("Raiz Cúbica");
        lblRaC.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        divRes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        divRes.setForeground(new java.awt.Color(0, 0, 255));
        divRes.setText("0");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Resto da Divisão por 2");

        javax.swing.GroupLayout panCalcLayout = new javax.swing.GroupLayout(panCalc);
        panCalc.setLayout(panCalcLayout);
        panCalcLayout.setHorizontalGroup(
            panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCalcLayout.createSequentialGroup()
                .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCalcLayout.createSequentialGroup()
                        .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRaC)
                            .addComponent(lblAbl)
                            .addComponent(lblPot)
                            .addComponent(lblRaQ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(potRes, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(raqRes, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(racRes, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ablRes, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(panCalcLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                        .addComponent(divRes)))
                .addContainerGap())
        );
        panCalcLayout.setVerticalGroup(
            panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCalcLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCalcLayout.createSequentialGroup()
                        .addGroup(panCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(divRes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPot)
                        .addGap(11, 11, 11)
                        .addComponent(lblRaQ)
                        .addGap(12, 12, 12)
                        .addComponent(lblRaC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCalcLayout.createSequentialGroup()
                        .addComponent(potRes)
                        .addGap(11, 11, 11)
                        .addComponent(raqRes)
                        .addGap(12, 12, 12)
                        .addComponent(racRes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ablRes))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(panCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClique, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClique, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(panCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCliqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliqueActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(txtNum.getValue().toString());
        divRes.setText(Integer.toString(num % 2));
        potRes.setText(Double.toString(Math.pow(num, 2)));
        double raiz = Math.sqrt(num);
        raqRes.setText(String.format("%.2f", raiz));
        raiz = Math.cbrt(num);
        racRes.setText(String.format("%.2f", raiz));
        ablRes.setText(Integer.toString(Math.abs(num)));
        panCalc.setVisible(true);
    }//GEN-LAST:event_btnCliqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ablRes;
    private javax.swing.JButton btnClique;
    private javax.swing.JLabel divRes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAbl;
    private javax.swing.JLabel lblPot;
    private javax.swing.JLabel lblRaC;
    private javax.swing.JLabel lblRaQ;
    private javax.swing.JPanel panCalc;
    private javax.swing.JLabel potRes;
    private javax.swing.JLabel racRes;
    private javax.swing.JLabel raqRes;
    private javax.swing.JSpinner txtNum;
    // End of variables declaration//GEN-END:variables
}
